spring:
  application:
    name: ai202
  ai:
    mcp:
      client:
        stdio:
#          servers-configuration: classpath:mcp-servers.json
          connections:
            server1:
              command: java
              args:
                - -jar
                - /Users/mark/dev/sessionrepos/mcpwx/target/mcpwx-0.0.1-SNAPSHOT.jar
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8080
#            server2:
#              url: http://otherserver:8081
    openai:
      image:
        options:
          size: 1024x1024
    vectorstore:
      qdrant:
        initialize-schema: true
  threads:
    virtual:
      enabled: true

#spring.ai.openai.audio.speech.options.voice=alloy (default, neutral American)
#spring.ai.openai.audio.speech.options.voice=echo (male-sounding American)
#spring.ai.openai.audio.speech.options.voice=fable (neutral British?)
#spring.ai.openai.audio.speech.options.voice=onyx (male-sounding American)
#spring.ai.openai.audio.speech.options.voice=nova (female-sounding American)
#spring.ai.openai.audio.speech.options.voice=shimmer (female-sounding American)
